routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\FakultasController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\MateriController;
use App\Http\Controllers\MenteeController;
use App\Http\Controllers\MentorController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\PengurusController;
use App\Http\Controllers\TahunAjarController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', [HomeController::class, 'home'])->middleware('auth')->name('home');

Auth::routes();

// Mentor routes
Route::middleware(['auth', 'user-access:mentor'])->prefix('mentor')->name('mentor.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::get('/materi', [MateriController::class, 'mentorIndex'])->name('materi.mentorIndex');
    Route::resource('/absensi', AbsensiController::class);
    Route::resource('/nilai', NilaiController::class);
    Route::get('/laporan', [LaporanController::class, 'laporanMentor'])->name('laporan.index');
});

// KMF routes
Route::middleware(['auth', 'user-access:kmf'])->prefix('kmf')->name('kmf.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'kmfIndex'])->name('dashboard');
    Route::get('/mentor', [MentorController::class, 'kmfIndex'])->name('mentor.index');
    Route::get('/mentee', [MenteeController::class, 'kmfIndex'])->name('mentee.index');
    Route::resource('/kelas', KelasController::class)->except(['create'])
        ->parameters(['kelas' => 'kelas']);
    Route::post('/add_mentee_to_kelas', [KelasController::class, 'add_mentee_to_kelas'])->name('add_mentee_to_kelas');
    Route::post('/remove_mentee_from_kelas', [KelasController::class, 'remove_mentee_from_kelas'])->name('remove_mentee_from_kelas');
    Route::get('/laporan', [LaporanController::class, 'laporanFakultas'])->name('laporan.index');
    Route::post('/laporan_filter', [LaporanController::class, 'laporanFilterFakultas'])->name('laporan.filter');
});

// KMP routesLove
Route::middleware(['auth', 'user-access:kmp'])->prefix('kmp')->name('kmp.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'kmpIndex'])->name('dashboard');
    Route::resource('/tahun_ajar', TahunAjarController::class)->except(['create', 'edit']);
    Route::post('/tahun_ajar_update_active', [TahunAjarController::class, 'update_active'])
        ->name('tahun_ajar_update_active');
    Route::resource('/fakultas', FakultasController::class)->except(['create', 'edit'])
        ->parameters(['fakultas' => 'fakultas']);
    Route::resource('/kelas', KelasController::class)->except(['create', 'edit'])
        ->parameters(['kelas' => 'kelas']);
    Route::resource('/pengurus', PengurusController::class)->except(['create', 'edit'])
        ->parameters(['pengurus' => 'pengurus']);
    Route::resource('/mentor', MentorController::class)->except(['create', 'edit']);
    Route::resource('/mentee', MenteeController::class)->except(['create', 'edit']);
    Route::resource('/materi', MateriController::class)->except(['create', 'edit']);

    // Import route
    Route::post('/import/pengurus', [ImportController::class, 'pengurus'])->name('import.pengurus');
    Route::post('/import/mentor', [ImportController::class, 'mentor'])->name('import.mentor');
    Route::post('/import/mentee', [ImportController::class, 'mentee'])->name('import.mentee');
});

Route::get('seeding-test', function () {
    $faker = Faker\Factory::create('id_ID');

    for ($i = 1; $i <= 50; $i++) {

        // insert data ke table pegawai menggunakan Faker
        DB::table('mentees')->insert([
            'nama' => $faker->name,
            'nim' => $faker->randomElement(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']) . $faker->randomNumber(9, true),
            'gender' => $faker->randomElement(['L', 'P']),
            'no_hp' => $faker->phoneNumber,
            'tahun_ajar_id' => 1,
            'fakultas_id' => $faker->numberBetween(1, 12)
        ]);
        DB::table('users')->insert([
            'nama' => $faker->name(),
            'username' => $faker->userName(),
            'email' => $faker->email(),
            'password' => bcrypt('password'),
            'fakultas_id' => $faker->numberBetween(1, 3),
            'role' => 'mentor'
        ]);
    }
});

app/Http/Controllers/PengurusController.php
<?php

namespace App\Http\Controllers;

use App\Models\Fakultas;
use App\Models\TahunAjar;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class PengurusController extends Controller
{
    public function index(Request $request)
    {
        if ($request->option == 'load_table_data') {
            $data = User::where('role', 'kmf')->get();
            return view('kmp.pengurus.table_data', compact('data'));
        }
        $fakultas = Fakultas::orderBy('nama')->get();
        return view('kmp.pengurus.index', compact('fakultas'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'fakultas_id' => 'required',
            'nama' => 'required',
            'username' => [
                'required',
                'alpha_dash:ascii',
                Rule::unique('users', 'username')->where(function ($query) {
                    return $query->where('role', 'kmf');
                }),
            ],
            'email' => [
                'required',
                'email',
                Rule::unique('users', 'email')->where(function ($query) {
                    return $query->where('role', 'kmf');
                }),
            ],
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        // Add data to database and send response
        User::create([
            'fakultas_id' => $request->fakultas_id,
            'nama' => ucwords($request->nama),
            'username' => strtolower($request->username),
            'email' => $request->email,
            'password' => bcrypt('password'),
            'role' => 'kmf',
        ]);
        return $this->notifyResponse('success', 'Submit succeeded', 'Your data has been successfully submited.');
    }

    public function show(User $pengurus)
    {
        return response()->json($pengurus);
    }

    public function update(Request $request, User $pengurus)
    {
        $validator = Validator::make($request->all(), [
            'fakultas_id' => 'required',
            'nama' => 'required',
            'username' => [
                'required',
                'alpha_dash:ascii',
                Rule::unique('users', 'username')->ignore($pengurus->id)->where(function ($query) {
                    return $query->where('role', 'kmf');
                }),
            ],
            'email' => [
                'required',
                'email',
                Rule::unique('users', 'email')->ignore($pengurus->id)->where(function ($query) {
                    return $query->where('role', 'kmf');
                }),
            ],
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        // Update data to database and send response
        $pengurus->update([
            'fakultas_id' => $request->fakultas_id,
            'nama' => ucwords($request->nama),
            'username' => strtolower($request->username),
            'email' => $request->email,
        ]);
        return $this->notifyResponse('success', 'Update succeeded', 'Your data has been successfully updated.');
    }

    public function destroy(User $pengurus)
    {
        $pengurus->delete();
        return $this->notifyResponse('success', 'Delete succeeded', 'Your data has been successfully deleted.');
    }

    private function notifyResponse($status, $title, $message)
    {
        return view('layouts.partials.notify', compact('status', 'title', 'message'));
    }
}

resources/views/kmp/pengurus/style_and_script.blade.php
@push('style')
    <style>
        .dataTables_length label,
        .dataTables_filter label {
            display: flex;
            gap: 8px;
        }

        .dataTables_paginate ul {
            margin: auto 0;
        }
    </style>
@endpush

@push('script')
    <script>
        // Load table data from ajax request
        loadDataTable("{{ url('kmp/pengurus?option=load_table_data') }}");

        $(document).ready(function() {
            // On form submit
            handleFormSubmitUpdate(
                $('#form-submit'), "{{ route('kmp.pengurus.store') }}",
                function(response) {
                    notify(response);
                    loadDataTable("{{ url('kmp/pengurus?option=load_table_data') }}");
                    clearForm($('#form-submit'));
                    $('#modal-add').modal('hide');
                },
                function(error) {
                    handleFormErrors(error, ['input', 'textarea', 'select']);
                });

            // On form update
            handleFormSubmitUpdate(
                $('#form-update'), "{{ url('kmp/pengurus') }}",
                function(response) {
                    notify(response);
                    loadDataTable("{{ url('kmp/pengurus?option=load_table_data') }}");
                    clearForm($('#form-update'));
                    $('#modal-update').modal('hide');
                },
                function(error) {
                    handleFormErrors(error, ['input', 'textarea', 'select']);
                });

            // On delete
            handleFormDelete(
                $('#form-delete'), "{{ url('kmp/pengurus') }}",
                function(response) {
                    loadDataTable("{{ url('kmp/pengurus?option=load_table_data') }}");
                    $('#modal-delete').modal('hide');
                    notify(response);
                });

            // On form import
            handleFormSubmitUpdate(
                $('#form-import'), "{{ route('kmp.import.pengurus') }}",
                function(response) {
                    notify(response);
                    loadDataTable("{{ url('kmp/pengurus?option=load_table_data') }}");
                    clearForm($('#form-import'));
                },
                function(error) {
                    handleFormErrors(error, ['input', 'textarea', 'select']);
                });

            // On add button click
            $(document).on('click', '.btn-add-data', function(e) {
                clearForm($('#form-submit'));
            });

            // On edit button click
            $(document).on('click', '.btn-edit-data', function(e) {
                clearForm($('#form-update'));
                let id = $(this).data('id');
                $.ajax({
                    url: "{{ url('kmp/pengurus') }}" + `/${id}`,
                    type: "GET",
                    cache: false,
                    success: function(response) {
                        //fill data to form
                        $('#form-update').find('input[name="id"]').val(response.id);
                        $('#form-update').find('select[name="fakultas_id"]').val(response
                            .fakultas_id).change();
                        $('#form-update').find('input[name="nama"]').val(response.nama);
                        $('#form-update').find('input[name="username"]').val(response.username);
                        $('#form-update').find('input[name="email"]').val(response.email);

                        //open modal
                        $('#modal-update').modal('show');
                    }
                });
            });

            // On delete button click
            $(document).on('click', '.btn-delete-data', function(e) {
                let id = $(this).data('id');
                $('#modal-delete').modal('show');
                $('#modal-delete').find('input[name="id"]').val(id);
            });
        });
    </script>
@endpush

resources/views/kmp/pengurus/table_data.blade.php
<div class="card-body border-bottom py-3">
    <div class="d-flex align-items-center justify-content-between">
        <div class="text-muted datatable-length"></div>
        <div class="ms-auto text-muted datatable-filter"></div>
    </div>
</div>
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable">
        <thead>
            <tr>
                <th class="w-1">No.</th>
                <th>Nama</th>
                <th>Username</th>
                <th>Email</th>
                <th>Fakultas</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @php
                $color = ['azure', 'indigo', 'purple', 'red', 'orange', 'yellow', 'lime ', 'cyan', 'green', 'pink', 'teal', 'blue'];
            @endphp
            @foreach ($data as $index => $item)
                <tr>
                    <td></td>
                    <td>{{ $item->nama }}</td>
                    <td>{{ $item->username }}</td>
                    <td>{{ $item->email }}</td>
                    <td>
                        <span class="badge bg-{{ $color[$item->fakultas->id - 1] }}">
                            {{ $item->fakultas->kode }}
                        </span>
                    </td>
                    <td class="text-end">
                        <button type="button" class="btn btn-edit-data" data-id="{{ $item->id }}">
                            <i class="ti ti-edit me-2"></i>
                            Edit
                        </button>
                        <button type="button" class="btn btn-delete-data" data-id="{{ $item->id }}">
                            <i class="ti ti-trash me-2"></i>
                            Delete
                        </button>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
<div class="card-footer d-flex align-items-center justify-content-between">
    <div class="datatable-info"></div>
    <div class="datatable-paginate"></div>
</div>