routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\FakultasController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\MateriController;
use App\Http\Controllers\MenteeController;
use App\Http\Controllers\MentorController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\PengurusController;
use App\Http\Controllers\TahunAjarController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', [HomeController::class, 'home'])->middleware('auth')->name('home');

Auth::routes();

// Mentor routes
Route::middleware(['auth', 'user-access:mentor'])->prefix('mentor')->name('mentor.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::get('/materi', [MateriController::class, 'mentorIndex'])->name('materi.mentorIndex');
    Route::resource('/absensi', AbsensiController::class);
    Route::resource('/nilai', NilaiController::class);
    Route::get('/laporan', [LaporanController::class, 'laporanMentor'])->name('laporan.index');
});

// KMF routes
Route::middleware(['auth', 'user-access:kmf'])->prefix('kmf')->name('kmf.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'kmfIndex'])->name('dashboard');
    Route::get('/mentor', [MentorController::class, 'kmfIndex'])->name('mentor.index');
    Route::get('/mentee', [MenteeController::class, 'kmfIndex'])->name('mentee.index');
    Route::resource('/kelas', KelasController::class)->except(['create'])
        ->parameters(['kelas' => 'kelas']);
    Route::post('/add_mentee_to_kelas', [KelasController::class, 'add_mentee_to_kelas'])->name('add_mentee_to_kelas');
    Route::post('/remove_mentee_from_kelas', [KelasController::class, 'remove_mentee_from_kelas'])->name('remove_mentee_from_kelas');
    Route::get('/laporan', [LaporanController::class, 'laporanFakultas'])->name('laporan.index');
    Route::post('/laporan_filter', [LaporanController::class, 'laporanFilterFakultas'])->name('laporan.filter');
});

// KMP routesLove
Route::middleware(['auth', 'user-access:kmp'])->prefix('kmp')->name('kmp.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'kmpIndex'])->name('dashboard');
    Route::resource('/tahun_ajar', TahunAjarController::class)->except(['create', 'edit']);
    Route::post('/tahun_ajar_update_active', [TahunAjarController::class, 'update_active'])
        ->name('tahun_ajar_update_active');
    Route::resource('/fakultas', FakultasController::class)->except(['create', 'edit'])
        ->parameters(['fakultas' => 'fakultas']);
    Route::resource('/kelas', KelasController::class)->except(['create', 'edit'])
        ->parameters(['kelas' => 'kelas']);
    Route::resource('/pengurus', PengurusController::class)->except(['create', 'edit'])
        ->parameters(['pengurus' => 'pengurus']);
    Route::resource('/mentor', MentorController::class)->except(['create', 'edit']);
    Route::resource('/mentee', MenteeController::class)->except(['create', 'edit']);
    Route::resource('/materi', MateriController::class)->except(['create', 'edit']);

    // Import route
    Route::post('/import/pengurus', [ImportController::class, 'pengurus'])->name('import.pengurus');
    Route::post('/import/mentor', [ImportController::class, 'mentor'])->name('import.mentor');
    Route::post('/import/mentee', [ImportController::class, 'mentee'])->name('import.mentee');
});

Route::get('seeding-test', function () {
    $faker = Faker\Factory::create('id_ID');

    for ($i = 1; $i <= 50; $i++) {

        // insert data ke table pegawai menggunakan Faker
        DB::table('mentees')->insert([
            'nama' => $faker->name,
            'nim' => $faker->randomElement(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']) . $faker->randomNumber(9, true),
            'gender' => $faker->randomElement(['L', 'P']),
            'no_hp' => $faker->phoneNumber,
            'tahun_ajar_id' => 1,
            'fakultas_id' => $faker->numberBetween(1, 12)
        ]);
        DB::table('users')->insert([
            'nama' => $faker->name(),
            'username' => $faker->userName(),
            'email' => $faker->email(),
            'password' => bcrypt('password'),
            'fakultas_id' => $faker->numberBetween(1, 3),
            'role' => 'mentor'
        ]);
    }
});

app/Models/Mentee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mentee extends Model
{
    use HasFactory;

    protected $fillable = ['tahun_ajar_id', 'fakultas_id', 'nama', 'nim', 'gender', 'no_hp', 'kelas_id'];

    protected $with = ['absensi', 'nilai'];

    public function tahun_ajar()
    {
        return $this->belongsTo(TahunAjar::class);
    }

    public function fakultas()
    {
        return $this->belongsTo(Fakultas::class, 'fakultas_id');
    }

    public function kelas()
    {
        return $this->belongsTo(Kelas::class, 'kelas_id');
    }

    public function absensi()
    {
        return $this->hasMany(Absensi::class);
    }

    public function nilai()
    {
        return $this->hasMany(Nilai::class);
    }
}

app/Http/Controllers/MenteeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Fakultas;
use App\Models\Mentee;
use App\Models\TahunAjar;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class MenteeController extends Controller
{
    public function index(Request $request)
    {
        if ($request->option == 'load_table_data') {
            $data = Mentee::all();
            return view('kmp.mentee.table_data', compact('data'));
        }
        $tahun_ajar = TahunAjar::where('active', true)->first();
        $fakultas = Fakultas::orderBy('nama')->get();
        return view('kmp.mentee.index', compact('tahun_ajar', 'fakultas'));
    }

    public function kmfIndex(Request $request)
    {
        if ($request->option == 'load_table_data') {
            $data = Mentee::where('fakultas_id', Auth::user()->fakultas_id)->orderBy('nama')->get();
            return view('kmf.mentee.table_data', compact('data'));
        }
        return view('kmf.mentee.index');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'fakultas_id' => 'required',
            'nama' => 'required',
            'nim' => 'required|unique:mentees,nim',
            'gender' => 'required',
            'no_hp' => 'required|unique:mentees,no_hp',
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        // Add data to database and send response
        Mentee::create([
            'tahun_ajar_id' => $request->tahun_ajar_id,
            'fakultas_id' => $request->fakultas_id,
            'nama' => ucwords($request->nama),
            'nim' => strtoupper($request->nim),
            'gender' => $request->gender,
            'no_hp' => $request->no_hp,
        ]);
        return $this->notifyResponse('success', 'Submit succeeded', 'Your data has been successfully submited.');
    }

    public function show(Mentee $mentee)
    {
        return response()->json($mentee);
    }

    public function update(Request $request, Mentee $mentee)
    {
        $validator = Validator::make($request->all(), [
            'fakultas_id' => 'required',
            'nama' => 'required',
            'nim' => 'required|unique:mentees,nim,' . $mentee->id,
            'gender' => 'required',
            'no_hp' => 'required|unique:mentees,no_hp,' . $mentee->id,
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        // Update data to database and send response
        $mentee->update([
            'fakultas_id' => $request->fakultas_id,
            'nama' => ucwords($request->nama),
            'nim' => strtoupper($request->nim),
            'gender' => $request->gender,
            'no_hp' => $request->no_hp,
        ]);
        return $this->notifyResponse('success', 'Update succeeded', 'Your data has been successfully updated.');
    }

    public function destroy(Mentee $mentee)
    {
        $mentee->delete();
        return $this->notifyResponse('success', 'Delete succeeded', 'Your data has been successfully deleted.');
    }

    private function notifyResponse($status, $title, $message)
    {
        return view('layouts.partials.notify', compact('status', 'title', 'message'));
    }
}

resources/views/kmp/mentee/style_and_script.blade.php
@push('style')
    <style>
        .dataTables_length label,
        .dataTables_filter label {
            display: flex;
            gap: 8px;
        }

        .dataTables_paginate ul {
            margin: auto 0;
        }

        input[type="number"] {
            -moz-appearance: textfield;
        }

        input[type="number"]::-webkit-outer-spin-button,
        input[type="number"]::-webkit-inner-spin-button {
            display: none;
        }
    </style>
@endpush

@push('script')
    <script>
        // Load table data from ajax request
        loadDataTable("{{ url('kmp/mentee?option=load_table_data') }}");

        $(document).ready(function() {
            // On form submit
            handleFormSubmitUpdate(
                $('#form-submit'), "{{ route('kmp.mentee.store') }}",
                function(response) {
                    notify(response);
                    loadDataTable("{{ url('kmp/mentee?option=load_table_data') }}");
                    clearForm($('#form-submit'));
                    $('#modal-add').modal('hide');
                },
                function(error) {
                    handleFormErrors(error, ['input', 'textarea', 'select']);
                });

            // On form update
            handleFormSubmitUpdate(
                $('#form-update'), "{{ url('kmp/mentee') }}",
                function(response) {
                    notify(response);
                    loadDataTable("{{ url('kmp/mentee?option=load_table_data') }}");
                    clearForm($('#form-update'));
                    $('#modal-update').modal('hide');
                },
                function(error) {
                    handleFormErrors(error, ['input', 'textarea', 'select']);
                });

            // On delete
            handleFormDelete(
                $('#form-delete'), "{{ url('kmp/mentee') }}",
                function(response) {
                    loadDataTable("{{ url('kmp/mentee?option=load_table_data') }}");
                    $('#modal-delete').modal('hide');
                    notify(response);
                });

            // On form import
            handleFormSubmitUpdate(
                $('#form-import'), "{{ route('kmp.import.mentee') }}",
                function(response) {
                    notify(response);
                    loadDataTable("{{ url('kmp/mentee?option=load_table_data') }}");
                    clearForm($('#form-import'));
                },
                function(error) {
                    console.log(error);
                    handleFormErrors(error, ['input', 'textarea', 'select']);
                });

            // On add button click
            $(document).on('click', '.btn-add-data', function(e) {
                clearForm($('#form-submit'));
            });

            // On edit button click
            $(document).on('click', '.btn-edit-data', function(e) {
                clearForm($('#form-update'));
                let id = $(this).data('id');
                $.ajax({
                    url: "{{ url('kmp/mentee') }}" + `/${id}`,
                    type: "GET",
                    cache: false,
                    success: function(response) {
                        //fill data to form
                        $('#form-update').find('input[name="id"]').val(response.id);
                        $('#form-update').find('select[name="fakultas_id"]').val(response
                            .fakultas_id).change();
                        $('#form-update').find('input[name="nama"]').val(response.nama);
                        $('#form-update').find('input[name="nim"]').val(response.nim);
                        $('#form-update').find('select[name="gender"]').val(response
                            .gender).change();
                        $('#form-update').find('input[name="no_hp"]').val(response.no_hp);

                        //open modal
                        $('#modal-update').modal('show');
                    }
                });
            });

            // On delete button click
            $(document).on('click', '.btn-delete-data', function(e) {
                let id = $(this).data('id');
                $('#modal-delete').modal('show');
                $('#modal-delete').find('input[name="id"]').val(id);
            });
        });
    </script>
@endpush

resources/views/kmp/mentee/table_data.blade.php
<div class="card-body border-bottom py-3">
    <div class="d-flex align-items-center justify-content-between">
        <div class="text-muted datatable-length"></div>
        <div class="ms-auto text-muted datatable-filter"></div>
    </div>
</div>
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable">
        <thead>
            <tr>
                <th class="w-1">No.</th>
                <th>#</th>
                <th>Nama</th>
                <th>NIM</th>
                <th>Gender</th>
                <th>Fakultas</th>
                <th>No. HP</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @php
                $color = ['azure', 'indigo', 'purple', 'red', 'orange', 'yellow', 'lime ', 'cyan', 'green', 'pink', 'teal', 'blue'];
            @endphp
            @foreach ($data as $index => $item)
                <tr>
                    <td></td>
                    <td>{{ $item->fakultas->kode . ' - ' . $item->tahun_ajar->tahun_ajar }}</td>
                    <td>{{ $item->nama }}</td>
                    <td>{{ $item->nim }}</td>
                    <td>
                        <span class="badge bg-{{ $item->gender == 'L' ? 'azure' : 'pink' }}">
                            {{ $item->gender }}
                        </span>
                    </td>
                    <td>
                        <span class="badge bg-{{ $color[$item->fakultas->id - 1] }}">
                            {{ $item->fakultas->kode }}
                        </span>
                    </td>
                    <td>{{ $item->no_hp }}</td>
                    <td class="text-end">
                        <button type="button" class="btn btn-edit-data" data-id="{{ $item->id }}">
                            <i class="ti ti-edit me-2"></i>
                            Edit
                        </button>
                        <button type="button" class="btn btn-delete-data" data-id="{{ $item->id }}">
                            <i class="ti ti-trash me-2"></i>
                            Delete
                        </button>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
<div class="card-footer d-flex align-items-center justify-content-between">
    <div class="datatable-info"></div>
    <div class="datatable-paginate"></div>
</div>