routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\FakultasController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\MateriController;
use App\Http\Controllers\MenteeController;
use App\Http\Controllers\MentorController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\PengurusController;
use App\Http\Controllers\TahunAjarController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', [HomeController::class, 'home'])->middleware('auth')->name('home');

Auth::routes();

// Mentor routes
Route::middleware(['auth', 'user-access:mentor'])->prefix('mentor')->name('mentor.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::get('/materi', [MateriController::class, 'mentorIndex'])->name('materi.mentorIndex');
    Route::resource('/absensi', AbsensiController::class);
    Route::resource('/nilai', NilaiController::class);
    Route::get('/laporan', [LaporanController::class, 'laporanMentor'])->name('laporan.index');
});

// KMF routes
Route::middleware(['auth', 'user-access:kmf'])->prefix('kmf')->name('kmf.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'kmfIndex'])->name('dashboard');
    Route::get('/mentor', [MentorController::class, 'kmfIndex'])->name('mentor.index');
    Route::get('/mentee', [MenteeController::class, 'kmfIndex'])->name('mentee.index');
    Route::resource('/kelas', KelasController::class)->except(['create'])
        ->parameters(['kelas' => 'kelas']);
    Route::post('/add_mentee_to_kelas', [KelasController::class, 'add_mentee_to_kelas'])->name('add_mentee_to_kelas');
    Route::post('/remove_mentee_from_kelas', [KelasController::class, 'remove_mentee_from_kelas'])->name('remove_mentee_from_kelas');
    Route::get('/laporan', [LaporanController::class, 'laporanFakultas'])->name('laporan.index');
    Route::post('/laporan_filter', [LaporanController::class, 'laporanFilterFakultas'])->name('laporan.filter');
});

// KMP routesLove
Route::middleware(['auth', 'user-access:kmp'])->prefix('kmp')->name('kmp.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'kmpIndex'])->name('dashboard');
    Route::resource('/tahun_ajar', TahunAjarController::class)->except(['create', 'edit']);
    Route::post('/tahun_ajar_update_active', [TahunAjarController::class, 'update_active'])
        ->name('tahun_ajar_update_active');
    Route::resource('/fakultas', FakultasController::class)->except(['create', 'edit'])
        ->parameters(['fakultas' => 'fakultas']);
    Route::resource('/kelas', KelasController::class)->except(['create', 'edit'])
        ->parameters(['kelas' => 'kelas']);
    Route::resource('/pengurus', PengurusController::class)->except(['create', 'edit'])
        ->parameters(['pengurus' => 'pengurus']);
    Route::resource('/mentor', MentorController::class)->except(['create', 'edit']);
    Route::resource('/mentee', MenteeController::class)->except(['create', 'edit']);
    Route::resource('/materi', MateriController::class)->except(['create', 'edit']);

    // Import route
    Route::post('/import/pengurus', [ImportController::class, 'pengurus'])->name('import.pengurus');
    Route::post('/import/mentor', [ImportController::class, 'mentor'])->name('import.mentor');
    Route::post('/import/mentee', [ImportController::class, 'mentee'])->name('import.mentee');
});

Route::get('seeding-test', function () {
    $faker = Faker\Factory::create('id_ID');

    for ($i = 1; $i <= 50; $i++) {

        // insert data ke table pegawai menggunakan Faker
        DB::table('mentees')->insert([
            'nama' => $faker->name,
            'nim' => $faker->randomElement(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']) . $faker->randomNumber(9, true),
            'gender' => $faker->randomElement(['L', 'P']),
            'no_hp' => $faker->phoneNumber,
            'tahun_ajar_id' => 1,
            'fakultas_id' => $faker->numberBetween(1, 12)
        ]);
        DB::table('users')->insert([
            'nama' => $faker->name(),
            'username' => $faker->userName(),
            'email' => $faker->email(),
            'password' => bcrypt('password'),
            'fakultas_id' => $faker->numberBetween(1, 3),
            'role' => 'mentor'
        ]);
    }
});

app/Models/Absensi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Absensi extends Model
{
    use HasFactory;

    protected $fillable = ['kelas_id', 'mentee_id', 'pertemuan', 'kehadiran'];

    public function kelas()
    {
        return $this->belongsTo(Kelas::class, 'kelas_id');
    }

    public function mentee()
    {
        return $this->belongsTo(Mentee::class);
    }
}

app/Http/Controllers/AbsensiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Absensi;
use App\Models\BuktiKegiatan;
use App\Models\Kelas;
use App\Models\Mentee;
use App\Models\TahunAjar;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class AbsensiController extends Controller
{
    public function index(Request $request)
    {
        $tahun_ajar = TahunAjar::where('active', true)->first();
        $mentor = Auth::user();
        $kelas = Kelas::where('tahun_ajar_id', $tahun_ajar->id)
            ->where('mentor_id', $mentor->id)->first();

        if ($request->option == 'load_table_data') {
            $bukti = BuktiKegiatan::where('kelas_id', $kelas->id)
                ->where('pertemuan', $request->pertemuan)->first();
            $data = Mentee::select('mentees.*', 'absensis.id as absensi', 'absensis.kehadiran')
                ->leftJoin('absensis', 'absensis.mentee_id', '=', 'mentees.id')
                ->where('mentees.kelas_id', $kelas->id)
                ->where('absensis.kelas_id', $kelas->id)
                ->where('absensis.pertemuan', $request->pertemuan)
                ->get();
            if (!$bukti) {
                $this->_setup_bukti($kelas->id, $request->pertemuan);
                $bukti = BuktiKegiatan::where('kelas_id', $kelas->id)
                    ->where('pertemuan', $request->pertemuan)->first();
            }
            if ($data->isEmpty()) {
                $this->_setup_absensi($kelas->id, $request->pertemuan);
                $data = Mentee::select('mentees.*', 'absensis.id as absensi', 'absensis.kehadiran')
                    ->leftJoin('absensis', 'absensis.mentee_id', '=', 'mentees.id')
                    ->where('mentees.kelas_id', $kelas->id)
                    ->where('absensis.kelas_id', $kelas->id)
                    ->where('absensis.pertemuan', $request->pertemuan)
                    ->get();
            }
            return view('mentor.absensi.table_data', compact('bukti', 'data'));
        }

        return view('mentor.absensi.index', compact('kelas'));
    }

    public function store(Request $request)
    {
        if ($request->bukti_id) {
            $bukti = BuktiKegiatan::find($request->bukti_id);

            if (File::exists(public_path('file-uploads/bukti_kegiatan') . '/' . $bukti->file)) {
                File::delete(public_path('file-uploads/bukti_kegiatan') . '/' . $bukti->file);
            }
            $file = $request->file('file');
            $filename = $file->hashName();
            $file->move(public_path('file-uploads/bukti_kegiatan'), $filename);

            $bukti->update(['file' => $filename]);
            return $this->notifyResponse('success', 'Update succeeded', 'Your data has been successfully updated.');
        }

        $alldata = [];
        foreach ($request->kehadiran as $item) {
            $data = explode('-', $item);
            array_push($alldata, $data);
        }

        foreach ($alldata as $item) {
            Absensi::find($item[0])->update(['kehadiran' => $item[1]]);
        }
        return $this->notifyResponse('success', 'Update succeeded', 'Your data has been successfully updated.');
    }

    private function notifyResponse($status, $title, $message)
    {
        return view('layouts.partials.notify', compact('status', 'title', 'message'));
    }

    private function _setup_absensi($kelas_id, $pertemuan)
    {
        for ($i = 1; $i <= 14; $i++) {
            $data = Mentee::where('mentees.kelas_id', $kelas_id)
                ->get();
            foreach ($data as $item) {
                Absensi::create([
                    'kelas_id' => $kelas_id,
                    'mentee_id' => $item->id,
                    'pertemuan' => $i,
                    'kehadiran' => false,
                ]);
            }
        }
    }

    private function _setup_bukti($kelas_id, $pertemuan)
    {
        for ($i = 1; $i <= 14; $i++) {
            BuktiKegiatan::create([
                'kelas_id' => $kelas_id,
                'pertemuan' => $i,
            ]);
        }
    }
}

app/Http/Controllers/MentorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Fakultas;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class MentorController extends Controller
{
    public function index(Request $request)
    {
        if ($request->option == 'load_table_data') {
            $data = User::where('role', 'mentor')->get();
            return view('kmp.mentor.table_data', compact('data'));
        }
        $fakultas = Fakultas::orderBy('nama')->get();
        return view('kmp.mentor.index', compact('fakultas'));
    }

    public function kmfIndex(Request $request)
    {
        if ($request->option == 'load_table_data') {
            $data = User::where('role', 'mentor')->where('fakultas_id', Auth::user()->fakultas_id)->orderBy('nama')->get();
            return view('kmf.mentor.table_data', compact('data'));
        }
        return view('kmf.mentor.index');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'fakultas_id' => 'required',
            'nama' => 'required',
            'username' => [
                'required',
                'alpha_dash:ascii',
                Rule::unique('users', 'username')->where(function ($query) {
                    return $query->where('role', 'mentor');
                }),
            ],
            'email' => [
                'required',
                'email',
                Rule::unique('users', 'email')->where(function ($query) {
                    return $query->where('role', 'mentor');
                }),
            ],
            'fakultas_id' => 'required',
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        // Add data to database and send response
        User::create([
            'fakultas_id' => $request->fakultas_id,
            'nama' => ucwords($request->nama),
            'username' => strtolower($request->username),
            'email' => $request->email,
            'password' => bcrypt('password'),
            'role' => 'mentor',
        ]);
        return $this->notifyResponse('success', 'Submit succeeded', 'Your data has been successfully submited.');
    }

    public function show(User $mentor)
    {
        return response()->json($mentor);
    }

    public function update(Request $request, User $mentor)
    {
        $validator = Validator::make($request->all(), [
            'fakultas_id' => 'required',
            'nama' => 'required',
            'username' => [
                'required',
                'alpha_dash:ascii',
                Rule::unique('users', 'username')->ignore($mentor->id)->where(function ($query) {
                    return $query->where('role', 'mentor');
                }),
            ],
            'email' => [
                'required',
                'email',
                Rule::unique('users', 'email')->ignore($mentor->id)->where(function ($query) {
                    return $query->where('role', 'mentor');
                }),
            ],
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        // Update data to database and send response
        $mentor->update([
            'nama' => ucwords($request->nama),
            'username' => strtolower($request->username),
            'email' => $request->email,
        ]);
        return $this->notifyResponse('success', 'Update succeeded', 'Your data has been successfully updated.');
    }

    public function destroy(User $mentor)
    {
        $mentor->delete();
        return $this->notifyResponse('success', 'Delete succeeded', 'Your data has been successfully deleted.');
    }

    private function notifyResponse($status, $title, $message)
    {
        return view('layouts.partials.notify', compact('status', 'title', 'message'));
    }
}

resources/views/mentor/absensi/index.blade.php
@extends('layouts.app')
@section('page-title', 'Absensi')

@section('content')
    @if (!Auth::user()->kelas->isEmpty())
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h2 class="mb-4">Info Kelas</h2>
                    <div class="row g-3">
                        <div class="col-md">
                            <div class="form-label">Nama Kelas</div>
                            <div class="border rounded py-2 px-3">
                                {{ $kelas->nama }}
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-label">PJ Mentor</div>
                            <div class="border rounded py-2 px-3">
                                {{ $kelas->mentor->nama }}
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-label">Total Mentee</div>
                            <div class="border rounded py-2 px-3">
                                {{ $kelas->mentee->count() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Absensi</h3>
                    <div class="card-actions">
                        <form action="javascript:void(0)" method="post" id="form-pertemuan">
                            <div class="input-group">
                                @csrf
                                @method('post')
                                <input type="hidden" name="kelas_id" value="{{ $kelas->id }}">
                                <select name="pertemuan" class="form-select">
                                    @for ($i = 1; $i <= 14; $i++)
                                        <option value="{{ $i }}">Pertemuan {{ $i }}</option>
                                    @endfor
                                </select>
                                <button type="submit" class="btn btn-primary">Go</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="content-data">
                    <div class="card-body">
                        <div class="alert alert-secondary">
                            <h4 class="alert-title">Pilih pertemuan!</h4>
                            <div class="text-secondary">Data akan ditampilkan sesuai dengan pertemuan yg dipilih!</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div class="col">
            <div class="alert alert-info w-100" role="alert">
                <h4 class="alert-title">Oops!</h4>
                <div class="text-secondary">Anda tidak memiliki kelas aktif!</div>
            </div>
        </div>
    @endif
@endsection

@include('mentor.absensi.style_and_script')

resources/views/mentor/absensi/style_and_script.blade.php
@push('script')
    <script>
        $(document).ready(function() {
            // Pertemuan submit
            $('#form-pertemuan').submit(function(e) {
                e.preventDefault();
                let pertemuan = $(this).find('select[name="pertemuan"]').val();
                $('.content-data').empty().html(`
                    <div class="col p-4">
                    <div class="placeholder placeholder-xs col-9"></div>
                    <div class="placeholder placeholder-xs col-7"></div>
                    <div class="placeholder placeholder-xs col-4"></div>
                    </div>
                `);
                loadDataTable("{{ url('mentor/absensi?option=load_table_data') }}" +
                    `&pertemuan=${pertemuan}`);
            });

            // Upload bukti
            $(document).on('submit', '#form-bukti', function(e) {
                e.preventDefault();
                let formdata = new FormData(this);

                $.ajax({
                    url: "{{ route('mentor.absensi.store') }}",
                    type: 'post',
                    data: formdata,
                    processData: false,
                    contentType: false,
                    cache: false,
                    success: function(response) {
                        notify(response);
                        $('#form-pertemuan').trigger('submit');
                    }
                })
            });

            // Save kehadiran
            $(document).on('submit', '#form-kehadiran', function(e) {
                e.preventDefault();
                let formdata = new FormData(this);

                $.ajax({
                    url: "{{ route('mentor.absensi.store') }}",
                    type: 'post',
                    data: formdata,
                    processData: false,
                    contentType: false,
                    cache: false,
                    success: function(response) {
                        notify(response);
                        $('#form-pertemuan').trigger('submit');
                    }
                })
            });
        });
    </script>
@endpush

resources/views/mentor/absensi/table_data.blade.php
<div class="card-body">
    <div class="accordion" id="accordion-example">
        <div class="accordion-item">
            <h2 class="accordion-header" id="heading-1">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapse-1" aria-expanded="false">
                    @if ($bukti->file == null)
                        <span class="badge bg-red-lt">Belum upload bukti</span>
                    @else
                        Bukti Kegiatan
                    @endif
                </button>
            </h2>
            <div id="collapse-1" class="accordion-collapse collapse" data-bs-parent="#accordion-example" style="">
                <div class="accordion-body pt-0">
                    @if ($bukti->file != null)
                        <img src="{{ asset('file-uploads/bukti_kegiatan') . '/' . $bukti->file }}"
                            class="img-fluid mx-auto border mb-3" alt="">
                    @endif
                    <form action="javascript:void(0)" id="form-bukti" method="post">
                        @csrf
                        @method('post')
                        @if ($bukti->file != null)
                            <span class="text-muted mb-1">Upload ulang untuk mengganti file.</span>
                        @endif
                        <div class="d-flex align-items-center gap-2">
                            <input type="hidden" name="bukti_id" value="{{ $bukti->id }}">
                            <input type="file" name="file" id="" class="form-control" required>
                            <button class="btn btn-primary">Upload</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<form id="form-kehadiran" action="javascript:void(0)" method="post">
    @csrf
    @method('post')
    <div class="table-responsive">
        <table class="table card-table table-vcenter text-nowrap">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Mentee</th>
                    <th>Kehadiran</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $index => $item)
                    <tr>
                        <td>{{ $index += 1 }}</td>
                        <td>{{ $item->nama }}</td>
                        <td>
                            <select name="kehadiran[]"
                                class="form-select {{ $item->kehadiran == true ? 'is-valid' : 'is-invalid' }}">
                                <option value="{{ $item->absensi . '-' . '1' }}"
                                    {{ $item->kehadiran == true ? 'selected' : '' }}>Hadir
                                </option>
                                <option value="{{ $item->absensi . '-' . '0' }}"
                                    {{ $item->kehadiran == false ? 'selected' : '' }}>Tidak hadir</option>
                            </select>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>