routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\FakultasController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\MateriController;
use App\Http\Controllers\MenteeController;
use App\Http\Controllers\MentorController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\PengurusController;
use App\Http\Controllers\TahunAjarController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', [HomeController::class, 'home'])->middleware('auth')->name('home');

Auth::routes();

// Mentor routes
Route::middleware(['auth', 'user-access:mentor'])->prefix('mentor')->name('mentor.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::get('/materi', [MateriController::class, 'mentorIndex'])->name('materi.mentorIndex');
    Route::resource('/absensi', AbsensiController::class);
    Route::resource('/nilai', NilaiController::class);
    Route::get('/laporan', [LaporanController::class, 'laporanMentor'])->name('laporan.index');
});

// KMF routes
Route::middleware(['auth', 'user-access:kmf'])->prefix('kmf')->name('kmf.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'kmfIndex'])->name('dashboard');
    Route::get('/mentor', [MentorController::class, 'kmfIndex'])->name('mentor.index');
    Route::get('/mentee', [MenteeController::class, 'kmfIndex'])->name('mentee.index');
    Route::resource('/kelas', KelasController::class)->except(['create'])
        ->parameters(['kelas' => 'kelas']);
    Route::post('/add_mentee_to_kelas', [KelasController::class, 'add_mentee_to_kelas'])->name('add_mentee_to_kelas');
    Route::post('/remove_mentee_from_kelas', [KelasController::class, 'remove_mentee_from_kelas'])->name('remove_mentee_from_kelas');
    Route::get('/laporan', [LaporanController::class, 'laporanFakultas'])->name('laporan.index');
    Route::post('/laporan_filter', [LaporanController::class, 'laporanFilterFakultas'])->name('laporan.filter');
});

// KMP routesLove
Route::middleware(['auth', 'user-access:kmp'])->prefix('kmp')->name('kmp.')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'kmpIndex'])->name('dashboard');
    Route::resource('/tahun_ajar', TahunAjarController::class)->except(['create', 'edit']);
    Route::post('/tahun_ajar_update_active', [TahunAjarController::class, 'update_active'])
        ->name('tahun_ajar_update_active');
    Route::resource('/fakultas', FakultasController::class)->except(['create', 'edit'])
        ->parameters(['fakultas' => 'fakultas']);
    Route::resource('/kelas', KelasController::class)->except(['create', 'edit'])
        ->parameters(['kelas' => 'kelas']);
    Route::resource('/pengurus', PengurusController::class)->except(['create', 'edit'])
        ->parameters(['pengurus' => 'pengurus']);
    Route::resource('/mentor', MentorController::class)->except(['create', 'edit']);
    Route::resource('/mentee', MenteeController::class)->except(['create', 'edit']);
    Route::resource('/materi', MateriController::class)->except(['create', 'edit']);

    // Import route
    Route::post('/import/pengurus', [ImportController::class, 'pengurus'])->name('import.pengurus');
    Route::post('/import/mentor', [ImportController::class, 'mentor'])->name('import.mentor');
    Route::post('/import/mentee', [ImportController::class, 'mentee'])->name('import.mentee');
});

Route::get('seeding-test', function () {
    $faker = Faker\Factory::create('id_ID');

    for ($i = 1; $i <= 50; $i++) {

        // insert data ke table pegawai menggunakan Faker
        DB::table('mentees')->insert([
            'nama' => $faker->name,
            'nim' => $faker->randomElement(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']) . $faker->randomNumber(9, true),
            'gender' => $faker->randomElement(['L', 'P']),
            'no_hp' => $faker->phoneNumber,
            'tahun_ajar_id' => 1,
            'fakultas_id' => $faker->numberBetween(1, 12)
        ]);
        DB::table('users')->insert([
            'nama' => $faker->name(),
            'username' => $faker->userName(),
            'email' => $faker->email(),
            'password' => bcrypt('password'),
            'fakultas_id' => $faker->numberBetween(1, 3),
            'role' => 'mentor'
        ]);
    }
});

app/Models/Nilai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Nilai extends Model
{
    use HasFactory;

    protected $fillable = ['kelas_id', 'mentee_id', 'pertemuan', 'nilai'];

    public function kelas()
    {
        return $this->belongsTo(Kelas::class, 'kelas_id');
    }

    public function mentee()
    {
        return $this->belongsTo(Mentee::class);
    }
}

app/Http/Controllers/MentorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Fakultas;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class MentorController extends Controller
{
    public function index(Request $request)
    {
        if ($request->option == 'load_table_data') {
            $data = User::where('role', 'mentor')->get();
            return view('kmp.mentor.table_data', compact('data'));
        }
        $fakultas = Fakultas::orderBy('nama')->get();
        return view('kmp.mentor.index', compact('fakultas'));
    }

    public function kmfIndex(Request $request)
    {
        if ($request->option == 'load_table_data') {
            $data = User::where('role', 'mentor')->where('fakultas_id', Auth::user()->fakultas_id)->orderBy('nama')->get();
            return view('kmf.mentor.table_data', compact('data'));
        }
        return view('kmf.mentor.index');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'fakultas_id' => 'required',
            'nama' => 'required',
            'username' => [
                'required',
                'alpha_dash:ascii',
                Rule::unique('users', 'username')->where(function ($query) {
                    return $query->where('role', 'mentor');
                }),
            ],
            'email' => [
                'required',
                'email',
                Rule::unique('users', 'email')->where(function ($query) {
                    return $query->where('role', 'mentor');
                }),
            ],
            'fakultas_id' => 'required',
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        // Add data to database and send response
        User::create([
            'fakultas_id' => $request->fakultas_id,
            'nama' => ucwords($request->nama),
            'username' => strtolower($request->username),
            'email' => $request->email,
            'password' => bcrypt('password'),
            'role' => 'mentor',
        ]);
        return $this->notifyResponse('success', 'Submit succeeded', 'Your data has been successfully submited.');
    }

    public function show(User $mentor)
    {
        return response()->json($mentor);
    }

    public function update(Request $request, User $mentor)
    {
        $validator = Validator::make($request->all(), [
            'fakultas_id' => 'required',
            'nama' => 'required',
            'username' => [
                'required',
                'alpha_dash:ascii',
                Rule::unique('users', 'username')->ignore($mentor->id)->where(function ($query) {
                    return $query->where('role', 'mentor');
                }),
            ],
            'email' => [
                'required',
                'email',
                Rule::unique('users', 'email')->ignore($mentor->id)->where(function ($query) {
                    return $query->where('role', 'mentor');
                }),
            ],
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        // Update data to database and send response
        $mentor->update([
            'nama' => ucwords($request->nama),
            'username' => strtolower($request->username),
            'email' => $request->email,
        ]);
        return $this->notifyResponse('success', 'Update succeeded', 'Your data has been successfully updated.');
    }

    public function destroy(User $mentor)
    {
        $mentor->delete();
        return $this->notifyResponse('success', 'Delete succeeded', 'Your data has been successfully deleted.');
    }

    private function notifyResponse($status, $title, $message)
    {
        return view('layouts.partials.notify', compact('status', 'title', 'message'));
    }
}

app/Http/Controllers/NilaiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kelas;
use App\Models\Mentee;
use App\Models\Nilai;
use App\Models\TahunAjar;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NilaiController extends Controller
{
    public function index(Request $request)
    {
        $tahun_ajar = TahunAjar::where('active', true)->first();
        $mentor = Auth::user();
        $kelas = Kelas::where('tahun_ajar_id', $tahun_ajar->id)
            ->where('mentor_id', $mentor->id)->first();

        if ($request->option == 'load_table_data') {
            $data = Mentee::select('mentees.*', 'nilais.id as nilai_id', 'nilais.nilai')
                ->leftJoin('nilais', 'nilais.mentee_id', '=', 'mentees.id')
                ->where('mentees.kelas_id', $kelas->id)
                ->where('nilais.kelas_id', $kelas->id)
                ->where('nilais.pertemuan', $request->pertemuan)
                ->get();
            if ($data->isEmpty()) {
                $this->_setup_nilai($kelas->id, $request->pertemuan);
                $data = Mentee::select('mentees.*', 'nilais.id as nilai_id', 'nilais.nilai')
                    ->leftJoin('nilais', 'nilais.mentee_id', '=', 'mentees.id')
                    ->where('mentees.kelas_id', $kelas->id)
                    ->where('nilais.kelas_id', $kelas->id)
                    ->where('nilais.pertemuan', $request->pertemuan)
                    ->get();
            }
            return view('mentor.nilai.table_data', compact('data'));
        }

        return view('mentor.nilai.index', compact('kelas'));
        //
    }

    public function store(Request $request)
    {
        $data = array_combine($request->nilai_id, $request->nilai);

        foreach ($data as $key => $value) {
            try {
                Nilai::find($key)->update(['nilai' => intval($value)]);
            } catch (\Throwable $th) {
                dd($th);
            }
        }
        return $this->notifyResponse('success', 'Update succeeded', 'Your data has been successfully updated.');
    }

    private function notifyResponse($status, $title, $message)
    {
        return view('layouts.partials.notify', compact('status', 'title', 'message'));
    }

    private function _setup_nilai($kelas_id, $pertemuan)
    {
        for ($i = 1; $i <= 14; $i++) {
            $data = Mentee::where('mentees.kelas_id', $kelas_id)
                ->get();
            foreach ($data as $item) {
                Nilai::create([
                    'kelas_id' => $kelas_id,
                    'mentee_id' => $item->id,
                    'pertemuan' => $i,
                    'nilai' => 0,
                ]);
            }
        }
    }
}

resources/views/mentor/nilai/index.blade.php
@extends('layouts.app')
@section('page-title', 'Nilai')

@section('content')
    @if (!Auth::user()->kelas->isEmpty())
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h2 class="mb-4">Info Kelas</h2>
                    <div class="row g-3">
                        <div class="col-md">
                            <div class="form-label">Nama Kelas</div>
                            <div class="border rounded py-2 px-3">
                                {{ $kelas->nama }}
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-label">PJ Mentor</div>
                            <div class="border rounded py-2 px-3">
                                {{ $kelas->mentor->nama }}
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-label">Total Mentee</div>
                            <div class="border rounded py-2 px-3">
                                {{ $kelas->mentee->count() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Absensi</h3>
                    <div class="card-actions">
                        <form action="javascript:void(0)" method="post" id="form-pertemuan">
                            <div class="input-group">
                                @csrf
                                @method('post')
                                <input type="hidden" name="kelas_id" value="{{ $kelas->id }}">
                                <select name="pertemuan" class="form-select">
                                    @for ($i = 1; $i <= 14; $i++)
                                        <option value="{{ $i }}">Pertemuan {{ $i }}</option>
                                    @endfor
                                </select>
                                <button type="submit" class="btn btn-primary">Go</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="content-data">
                    <div class="card-body">
                        <div class="alert alert-secondary">
                            <h4 class="alert-title">Pilih pertemuan!</h4>
                            <div class="text-secondary">Data akan ditampilkan sesuai dengan pertemuan yg dipilih!</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div class="col">
            <div class="alert alert-info w-100" role="alert">
                <h4 class="alert-title">Oops!</h4>
                <div class="text-secondary">Anda tidak memiliki kelas aktif!</div>
            </div>
        </div>
    @endif
@endsection

@include('mentor.nilai.style_and_script')

resources/views/mentor/nilai/style_and_script.blade.php
@push('script')
    <script>
        $(document).ready(function() {
            // Pertemuan submit
            $('#form-pertemuan').submit(function(e) {
                e.preventDefault();
                let pertemuan = $(this).find('select[name="pertemuan"]').val();
                $('.content-data').empty().html(`
                    <div class="col p-4">
                    <div class="placeholder placeholder-xs col-9"></div>
                    <div class="placeholder placeholder-xs col-7"></div>
                    <div class="placeholder placeholder-xs col-4"></div>
                    </div>
                `);
                loadDataTable("{{ url('mentor/nilai?option=load_table_data') }}" +
                    `&pertemuan=${pertemuan}`);
            });

            // Save nilai
            $(document).on('submit', '#form-nilai', function(e) {
                e.preventDefault();
                let formdata = new FormData(this);

                $.ajax({
                    url: "{{ route('mentor.nilai.store') }}",
                    type: 'post',
                    data: formdata,
                    processData: false,
                    contentType: false,
                    cache: false,
                    success: function(response) {
                        notify(response);
                        $('#form-pertemuan').trigger('submit');
                    }
                })
            });

            $(document).on('blur', 'input[name="nilai"]', function(e) {
                var value = $(this).val();
                if (value > 100) {
                    $(this).val(100);
                }
            });
        });
    </script>
@endpush

resources/views/mentor/nilai/table_data.blade.php
<form id="form-nilai" action="javascript:void(0)" method="post">
    @csrf
    @method('post')
    <div class="table-responsive">
        <table class="table card-table table-vcenter text-nowrap">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Mentee</th>
                    <th>Nilai</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $index => $item)
                    <tr>
                        <td>{{ $index += 1 }}</td>
                        <td>{{ $item->nama }}</td>
                        <td>
                            <input type="hidden" name="nilai_id[]" value="{{ $item->nilai_id }}">
                            <input type="number" name="nilai[]" class="form-control" min="0" max="100"
                                value="{{ $item->nilai }}">
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>